require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'sentryApp' do
  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'sentryAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Add <functional> to FlipperTransportTypes.h if missing
    installer.pods_project.targets.each do |target|
      if target.name == 'Flipper'
        file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
        if File.exist?(file_path)
          contents = File.read(file_path)
          unless contents.include?('#include <functional>')
            File.chmod(0755, file_path)
            File.open(file_path, 'w') do |file|
              file.puts('#include <functional>')
              file.puts(contents)
            end
          end
        end
      end
    end

    # Apply standard React Native post install
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )

    # Apply workaround for Xcode 12.5 M1
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Patch RCT-Folly Time.h iOS version macro
    time_header = 'Pods/RCT-Folly/folly/portability/Time.h'
    if File.exist?(time_header)
      text = File.read(time_header)
      new_contents = text.gsub('__IPHONE_10_0', '__IPHONE_12_0')
      File.open(time_header, 'w') { |file| file.puts new_contents }
    end
  end
end